chip_group: ipq60xx
platform: qualcommax
vendor: qualcomm

devices:
  - id: 8devices_mango-dvk
    name: 8Devices Mango-Dvk
  - id: alfa-network_ap120c-ax
    name: Alfa-Network Ap120C-Ax
  - id: anysafe_e1
    name: Anysafe E1
  - id: cambiumnetworks_xe3-4
    name: Cambiumnetworks Xe3-4
  - id: cmiot_ax18
    name: Cmiot Ax18
  - id: glinet_gl-ax1800
    name: Glinet Gl-Ax1800
  - id: glinet_gl-axt1800
    name: Glinet Gl-Axt1800
  - id: jdcloud_re-cs-02
    name: Jdcloud Re-Cs-02
  - id: jdcloud_re-cs-07
    name: Jdcloud Re-Cs-07
  - id: jdcloud_re-ss-01
    name: Jdcloud Re-Ss-01
  - id: kt_ar06-012h
    name: Kt Ar06-012H
  - id: lg_gapd-7500
    name: Lg Gapd-7500
  - id: link_nn6000-v1
    name: Link Nn6000-V1
  - id: link_nn6000-v2
    name: Link Nn6000-V2
  - id: linksys_mr7350
    name: Linksys Mr7350
  - id: linksys_mr7500
    name: Linksys Mr7500
  - id: netgear_rbr350
    name: Netgear Rbr350
  - id: netgear_rbs350
    name: Netgear Rbs350
  - id: netgear_wax214
    name: Netgear Wax214
  - id: netgear_wax610
    name: Netgear Wax610
  - id: netgear_wax610y
    name: Netgear Wax610Y
  - id: qihoo_360v6
    name: Qihoo 360V6
  - id: redmi_ax5
    name: Redmi Ax5
  - id: redmi_ax5-jdcloud
    name: Redmi Ax5-Jdcloud
  - id: tplink_eap610-outdoor
    name: Tplink Eap610-Outdoor
  - id: tplink_eap620-hd-v3
    name: Tplink Eap620-Hd-V3
  - id: tplink_eap623-outdoor-hd-v1
    name: Tplink Eap623-Outdoor-Hd-V1
  - id: tplink_eap625-outdoor-hd-v1
    name: Tplink Eap625-Outdoor-Hd-V1
  - id: xiaomi_ax1800
    name: Xiaomi Ax1800
  - id: yuncore_fap650
    name: Yuncore Fap650
  - id: zn_m2
    name: Zn M2
