chip_group: generic
platform: ipq806x
vendor: qualcomm

devices:
  - id: arris_tr4400-v2
    name: Arris Tr4400-V2
  - id: askey_rt4230w-rev6
    name: Askey Rt4230W-Rev6
  - id: asrock_g10
    name: Asrock G10
  - id: buffalo_wxr-2533dhp
    name: Buffalo Wxr-2533Dhp
  - id: compex_wpq864
    name: Compex Wpq864
  - id: edgecore_ecw5410
    name: Edgecore Ecw5410
  - id: extreme_ap3935
    name: Extreme Ap3935
  - id: fortinet_fap-421e
    name: Fortinet Fap-421E
  - id: ignitenet_ss-w2-ac2600
    name: Ignitenet Ss-W2-Ac2600
  - id: linksys_e8350-v1
    name: Linksys E8350-V1
  - id: linksys_ea7500-v1
    name: Linksys Ea7500-V1
  - id: linksys_ea8500
    name: Linksys Ea8500
  - id: meraki_mr42
    name: Meraki Mr42
  - id: meraki_mr52
    name: Meraki Mr52
  - id: nec_wg2600hp
    name: Nec Wg2600Hp
  - id: nec_wg2600hp3
    name: Nec Wg2600Hp3
  - id: netgear_d7800
    name: Netgear D7800
  - id: netgear_r7500
    name: Netgear R7500
  - id: netgear_r7500v2
    name: Netgear R7500V2
  - id: netgear_r7800
    name: Netgear R7800
  - id: netgear_xr450
    name: Netgear Xr450
  - id: netgear_xr500
    name: Netgear Xr500
  - id: nokia_ac400i
    name: Nokia Ac400I
  - id: qcom_ipq8064-ap148
    name: Qcom Ipq8064-Ap148
  - id: qcom_ipq8064-ap161
    name: Qcom Ipq8064-Ap161
  - id: qcom_ipq8064-db149
    name: Qcom Ipq8064-Db149
  - id: ruijie_rg-mtfi-m520
    name: Ruijie Rg-Mtfi-M520
  - id: tplink_ad7200
    name: Tplink Ad7200
  - id: tplink_c2600
    name: Tplink C2600
  - id: tplink_vr2600v
    name: Tplink Vr2600V
  - id: ubnt_unifi-ac-hd
    name: Ubnt Unifi-Ac-Hd
  - id: xiaomi_mi-router-hd
    name: Xiaomi Mi-Router-Hd
  - id: zyxel_nbg6817
    name: Zyxel Nbg6817
