chip_group: ipq6010
platform: ipq60xx
vendor: qualcomm

devices:
  - id: 8devices_mango-dvk
    name: 8devices Mango-DVK
  - id: anysafe_e1
    name: AnySafe E1
  - id: cambiumnetworks_xe3-4
    name: Cambium Networks XE3-4
  - id: jdcloud_re-cs-02
    name: JDCloud RE-CS-02
  - id: jdcloud_re-cs-07
    name: JDCloud RE-CS-07
  - id: netgear_wax214
    name: Netgear WAX214
  - id: netgear_wax610
    name: Netgear WAX610
  - id: netgear_wax610y
    name: Netgear WAX610Y
