chip_group: ipq807x
platform: qualcommax
vendor: qualcomm

devices:
  - id: aliyun_ap8220
    name: Aliyun Ap8220
  - id: arcadyan_aw1000
    name: Arcadyan Aw1000
  - id: asus_rt-ax89x
    name: Asus Rt-Ax89X
  - id: buffalo_wxr-5950ax12
    name: Buffalo Wxr-5950Ax12
  - id: cmcc_rm2-6
    name: Cmcc Rm2-6
  - id: compex_wpq873
    name: Compex Wpq873
  - id: dynalink_dl-wrx36
    name: Dynalink Dl-Wrx36
  - id: edgecore_eap102
    name: Edgecore Eap102
  - id: edimax_cax1800
    name: Edimax Cax1800
  - id: inseego_fg2000
    name: Inseego Fg2000
  - id: linksys_homewrk
    name: Linksys Homewrk
  - id: linksys_mx4200v1
    name: Linksys Mx4200V1
  - id: linksys_mx4200v2
    name: Linksys Mx4200V2
  - id: linksys_mx4300
    name: Linksys Mx4300
  - id: linksys_mx5300
    name: Linksys Mx5300
  - id: linksys_mx8500
    name: Linksys Mx8500
  - id: netgear_rax120v2
    name: Netgear Rax120V2
  - id: netgear_rbr750
    name: Netgear Rbr750
  - id: netgear_rbs750
    name: Netgear Rbs750
  - id: netgear_sxr80
    name: Netgear Sxr80
  - id: netgear_sxs80
    name: Netgear Sxs80
  - id: netgear_wax218
    name: Netgear Wax218
  - id: netgear_wax620
    name: Netgear Wax620
  - id: netgear_wax630
    name: Netgear Wax630
  - id: prpl_haze
    name: Prpl Haze
  - id: qnap_301w
    name: Qnap 301W
  - id: redmi_ax6
    name: Redmi Ax6
  - id: spectrum_sax1v1k
    name: Spectrum Sax1V1K
  - id: tcl_linkhub-hh500v
    name: Tcl Linkhub-Hh500V
  - id: tplink_deco-x80-5g
    name: Tplink Deco-X80-5G
  - id: tplink_eap620hd-v1
    name: Tplink Eap620Hd-V1
  - id: tplink_eap660hd-v1
    name: Tplink Eap660Hd-V1
  - id: verizon_cr1000a
    name: Verizon Cr1000A
  - id: xiaomi_ax3600
    name: Xiaomi Ax3600
  - id: xiaomi_ax9000
    name: Xiaomi Ax9000
  - id: yuncore_ax880
    name: Yuncore Ax880
  - id: zbtlink_zbt-z800ax
    name: Zbtlink Zbt-Z800Ax
  - id: zte_mf269
    name: Zte Mf269
  - id: zyxel_nbg7815
    name: Zyxel Nbg7815
  - id: zyxel_nwa110ax
    name: Zyxel Nwa110Ax
  - id: zyxel_nwa210ax
    name: Zyxel Nwa210Ax
