#!/bin/sh

# Set Chinese language as default for Luci
uci batch << EOF
set luci.main.lang=zh_cn
set luci.main.mediaurlbase=/luci-static/argon
commit luci
EOF

# Also set system locale to Chinese if possible
[ -f /etc/config/system ] && {
  uci set system.@system[0].zonename='Asia/Shanghai'
  uci set system.@system[0].timezone='CST-8'
  uci commit system
}

exit 0