// 完整的插件数据库 - 包含所有分类和详细功能

const PLUGINS = {
    proxy: [
        {name: 'HomeProxy', pkg: 'luci-app-homeproxy', desc: '高性能代理工具', version: 'v1.9.5', features: '支持多种协议、高性能转发、规则分流、日志记录'},
        {name: 'OpenClash', pkg: 'luci-app-openclash', desc: 'Clash 客户端', version: 'v0.45.87', features: '规则代理、节点切换、流量统计、订阅管理、Game 规则'},
        {name: 'PassWall', pkg: 'luci-app-passwall', desc: '综合代理工具', version: 'v2.8.3', features: '多协议支持、自动切换、负载均衡、节点测试'},
        {name: 'PassWall2', pkg: 'luci-app-passwall2', desc: 'PassWall 新版', version: 'v1.5.2', features: '新版架构、更好性能、更多协议、优化界面'},
        {name: 'SSR-Plus', pkg: 'luci-app-ssr-plus', desc: 'SS/SSR/Vmess 代理', version: 'v1.0', features: 'SS/SSR/Vmess/Trojan、规则分流、KCP 加速'},
        {name: 'Nikki', pkg: 'luci-app-nikki', desc: '代理工具', version: 'v1.2.0', features: '轻量级、多协议、规则分流、低资源占用'},
        {name: 'Momo', pkg: 'luci-app-momo', desc: '代理工具', version: 'v1.0.5', features: '简洁界面、快速连接、自动更新'},
        {name: 'FullCombo Shark!', pkg: 'luci-app-fc', desc: '全能代理', version: 'v3.0', features: '全能协议、一键配置、智能分流'},
        {name: 'luci-xray', pkg: 'luci-app-xray', desc: 'Xray 代理', version: 'v1.8.0', features: 'Xray 核心、VLESS/Vmess、XTLS、Reality'},
        {name: 'NeKoBox', pkg: 'luci-app-nekobox', desc: 'NekoBox 客户端', version: 'v1.0', features: 'Neko 核心、多协议、规则管理'},
        {name: 'v2rayA', pkg: 'luci-app-v2raya', desc: 'v2rayA 客户端', version: 'v1.5.0', features: 'v2ray 核心、Web 管理、多用户支持'}
    ],
    storage: [
        {name: 'DiskMan', pkg: 'luci-app-diskman', desc: '磁盘管理', version: 'v0.5.0', features: '分区管理、格式化、挂载、S.M.A.R.T 检测、RAID'},
        {name: 'Aria2', pkg: 'luci-app-aria2', desc: '下载工具', version: 'v1.1.0', features: 'HTTP/FTP/BT 下载、多线程、远程控制器、Web 界面'},
        {name: 'Qbittorrent', pkg: 'luci-app-qbittorrent', desc: 'BT 下载', version: 'v2.0', features: 'BT/磁力链、RSS 订阅、Web 控制、限速设置'},
        {name: 'Transmission', pkg: 'luci-app-transmission', desc: 'BT 下载', version: 'v1.1.0', features: '轻量 BT、Web 界面、计划任务、自动做种'},
        {name: 'Samba4', pkg: 'luci-app-samba4', desc: '文件共享', version: 'v1.0', features: 'SMB/CIFS 共享、权限管理、多用户访问'},
        {name: 'VSFTPD', pkg: 'luci-app-vsftpd', desc: 'FTP 服务器', version: 'v1.0', features: 'FTP 服务、匿名访问、用户认证、带宽限制'},
        {name: 'FileBrowser', pkg: 'luci-app-filebrowser', desc: '文件管理', version: 'v1.2.0', features: 'Web 文件管理、上传下载、在线预览、用户管理'},
        {name: 'WebDAV', pkg: 'luci-app-webdav', desc: 'WebDAV 服务', version: 'v1.0', features: 'WebDAV 协议、远程访问、加密传输'},
        {name: 'Aliyundrive', pkg: 'luci-app-aliyundrive-webdav', desc: '阿里云盘', version: 'v1.0', features: '阿里云盘 WebDAV、挂载本地、在线播放'},
        {name: 'Clouddrive2', pkg: 'luci-app-clouddrive2', desc: '多云盘管理', version: 'v2.0', features: '支持 20+ 云盘、WebDAV、挂载本地、自动同步'},
        {name: 'Cloudreve', pkg: 'luci-app-cloudreve', desc: '私有云盘', version: 'v1.0', features: '私有云存储、多用户、分享链接、在线预览'},
        {name: 'KodExplorer', pkg: 'luci-app-kodexplorer', desc: '可道云网盘', version: 'v1.0', features: '在线办公、文件管理、协同编辑、权限控制'},
        {name: 'Linkease', pkg: 'luci-app-linkease', desc: '易有云', version: 'v1.5.0', features: '文件管理、远程访问、数据备份'},
        {name: 'Rclone', pkg: 'luci-app-rclone', desc: '云盘同步', version: 'v1.0', features: '支持 50+ 云盘、同步备份、加密传输、定时任务'},
        {name: 'MiniDLNA', pkg: 'luci-app-minidlna', desc: 'DLNA 媒体服务器', version: 'v1.0', features: '媒体推送、智能电视播放、音乐流媒体'}
    ],
    network: [
        {name: 'Tailscale', pkg: 'luci-app-tailscale-community', desc: '虚拟组网', version: 'v1.3.0', features: '异地组网、P2P 直连、加密传输、跨平台'},
        {name: 'ZeroTier', pkg: 'luci-app-zerotier', desc: '内网穿透', version: 'v1.0', features: '虚拟局域网、跨网访问、免费节点、Moon 服务器'},
        {name: 'FRPC', pkg: 'luci-app-frpc', desc: '内网穿透客户端', version: 'v1.0', features: 'FRP 客户端、HTTP/TCP/UDP 穿透、HTTPS 支持'},
        {name: 'FRPS', pkg: 'luci-app-frps', desc: 'FRP 服务端', version: 'v1.0', features: 'FRP 服务端、多客户端管理、仪表盘'},
        {name: 'DDNS', pkg: 'luci-app-ddns', desc: '动态 DNS', version: 'v1.0', features: '域名解析、自动更新、支持 20+ 服务商'},
        {name: 'DDNS-GO', pkg: 'luci-app-ddns-go', desc: '动态 DNS', version: 'v1.0', features: '轻量 DDNS、支持阿里云/腾讯云/Cloudflare、Web 界面'},
        {name: 'MosDNS', pkg: 'luci-app-mosdns', desc: 'DNS 转发', version: 'v5.2.0', features: 'DNS 分流、去广告、缓存加速、DoH/DoT 加密'},
        {name: 'SmartDNS', pkg: 'luci-app-smartdns', desc: '智能 DNS', version: 'v1.0', features: '多上游 DNS、IP 优选、防污染、加速解析、自定义规则'},
        {name: 'Lucky', pkg: 'luci-app-lucky', desc: '多功能工具', version: 'v1.0', features: '端口转发、DDNS、Web 服务、反向代理、IPv6 支持'},
        {name: 'OpenList2', pkg: 'luci-app-openlist2', desc: '文件列表', version: 'v1.0', features: '原 Alist、多存储支持、在线播放、WebDAV'},
        {name: 'EasyTier', pkg: 'luci-app-easytier', desc: '异地组网', version: 'v1.0', features: '去中心化组网、自动 NAT 穿透、低延迟'},
        {name: 'WireGuard', pkg: 'luci-app-wireguard', desc: 'VPN', version: 'v1.0', features: 'WireGuard 协议、高性能、低延迟、移动端支持'},
        {name: 'OpenVPN', pkg: 'luci-app-openvpn-server-client', desc: 'OpenVPN', version: 'v1.0', features: 'OpenVPN 服务端/客户端、SSL 加密、证书管理'},
        {name: 'QoS', pkg: 'luci-app-qosmate', desc: '流量控制', version: 'v1.0', features: '带宽管理、优先级设置、实时监控、智能限速'},
        {name: 'SQM', pkg: 'luci-app-sqm-autorate', desc: 'QoS 控制', version: 'v1.0', features: '智能队列管理、自动速率调整、降低延迟'},
        {name: 'Netdata', pkg: 'luci-app-netdata', desc: '性能监测', version: 'v1.0', features: '实时性能监控、图表展示、告警通知、历史数据'},
        {name: 'FastNet', pkg: 'luci-app-fastnet', desc: '网络体检/测速', version: 'v1.0', features: '网络诊断、速度测试、延迟检测、路由追踪'},
        {name: 'NLBWmon', pkg: 'luci-app-nlbwmon', desc: '流量统计', version: 'v1.0', features: '按 IP 统计、历史数据、导出报表、实时监控'},
        {name: 'NPC', pkg: 'luci-app-npc', desc: 'NPS 客户端', version: 'v1.0', features: 'NPS 内网穿透、多协议支持、加密传输'},
        {name: 'DDNSTO', pkg: 'luci-app-ddnsto', desc: '内网穿透', version: 'v1.0', features: '免费内网穿透、HTTPS 访问、多线路'},
        {name: 'NATMap', pkg: 'luci-app-natmap', desc: '端口映射', version: 'v1.0', features: '自动端口映射、UPnP、NAT-PMP、STUN'},
        {name: 'Socat', pkg: 'luci-app-socat', desc: '端口转发', version: 'v1.0', features: 'TCP/UDP 转发、SSL 加密、多路复用'},
        {name: 'Thunder', pkg: 'luci-app-thunder', desc: '迅雷下载', version: 'v1.0', features: '迅雷下载、远程下载、离线下载、云盘备份'},
        {name: 'BandiX', pkg: 'luci-app-bandix', desc: '流量监控限速', version: 'v1.0', features: '实时流量、限速设置、设备管理、历史记录'},
        {name: 'EqOS', pkg: 'luci-app-eqosplus', desc: 'IP 限速', version: 'v1.0', features: '按 IP 限速、上下行控制、优先级设置'},
        {name: 'My DNSFilter', pkg: 'luci-app-my-dnsfilter', desc: 'DNS 去广告', version: 'v1.0', features: 'DNS 过滤、广告屏蔽、自定义规则、家长控制'},
        {name: 'AdGuardHome', pkg: 'luci-app-adguardhome', desc: 'ADG 去广告', version: 'v1.0', features: 'DNS 去广告、家长控制、隐私保护、统计报表'},
        {name: 'AdByBy', pkg: 'luci-app-adbyby-plus', desc: '去广告', version: 'v1.0', features: '规则去广告、视频广告过滤、网页净化'},
        {name: 'OAF', pkg: 'luci-app-oaf', desc: '应用过滤', version: 'v1.0', features: '应用识别、行为管理、上网行为分析、时间控制'},
        {name: 'MWAN3', pkg: 'luci-app-mwan3', desc: '负载均衡', version: 'v1.0', features: '多 WAN 口、负载均衡、故障转移、策略路由'},
        {name: 'IPTV Helper', pkg: 'luci-app-iptvhelper', desc: 'IPTV 助手', version: 'v1.0', features: 'IPTV 组播、UDP 转 HTTP、节目单管理'},
        {name: 'EasyMesh', pkg: 'luci-app-easymesh', desc: 'Mesh 组网', version: 'v1.0', features: 'Mesh 网络、无缝漫游、自动优化'},
        {name: 'TurboACC', pkg: 'luci-app-turboacc', desc: '网络加速', version: 'v1.0', features: '硬件加速、流量加速、NAT 加速、BBR 优化'},
        {name: 'Btop', pkg: 'btop', desc: '性能监控', version: 'v1.0', features: '系统监控、资源占用、进程管理、图表展示'},
        {name: 'NaiveProxy', pkg: 'naiveproxy', desc: '代理工具', version: 'v1.0', features: '轻量代理、HTTPS 传输、低延迟'}
    ],
    theme: [
        {name: 'Argon', pkg: 'luci-theme-argon', desc: '流行主题', version: 'v3.2.1', features: '毛玻璃效果、多种配色、自定义背景、响应式设计'},
        {name: 'Aurora', pkg: 'luci-theme-aurora', desc: '极光主题', version: 'v1.5.0', features: '渐变效果、夜间模式、简洁界面'},
        {name: 'Kucat', pkg: 'luci-theme-kucat', desc: '可爱主题', version: 'v1.0', features: '多彩配色、圆角设计、卡通风格'},
        {name: 'Material', pkg: 'luci-theme-material', desc: 'Material 设计', version: 'v1.0', features: 'Material Design、卡片布局、动画效果'},
        {name: 'Material3', pkg: 'luci-theme-material3', desc: 'Material3', version: 'v1.0', features: 'Material3 设计、新配色系统、动态主题'},
        {name: 'Design', pkg: 'luci-theme-design', desc: 'neobird 改版', version: 'v1.0', features: '现代化界面、简洁风格、优化布局'},
        {name: 'Alpha', pkg: 'luci-theme-alpha', desc: 'Alpha 主题', version: 'v1.0', features: '简洁风格、清爽界面'},
        {name: 'Spectra', pkg: 'luci-theme-spectra', desc: 'Spectra 主题', version: 'v1.0', features: '多彩渐变、现代感强'},
        {name: 'Routerich', pkg: 'luci-theme-routerich', desc: 'Routerich 主题', version: 'v1.0', features: '专业风格、商务范'},
        {name: 'Lightblue', pkg: 'luci-theme-lightblue', desc: '浅蓝主题', version: 'v1.0', features: '清爽界面、蓝色系'},
        {name: 'OpenWrt2020', pkg: 'luci-theme-openwrt-2020', desc: 'OpenWrt2020', version: 'v1.0', features: '经典风格、传统界面'},
        {name: 'OpenWrt', pkg: 'luci-theme-openwrt', desc: '经典主题', version: 'v1.0', features: '原始风格、怀旧经典'},
        {name: 'Teleofis', pkg: 'luci-theme-teleofis', desc: 'Teleofis 主题', version: 'v1.0', features: '工业风格、专业感'}
    ],
    system: [
        {name: 'TTYD', pkg: 'luci-app-ttyd', desc: '网页终端', version: 'v1.0', features: 'SSH 访问、多会话支持、Web 命令行'},
        {name: 'Automount', pkg: 'automount', desc: '自动挂载', version: 'v1.0', features: 'USB 设备识别、热插拔支持、自动挂载'},
        {name: 'HD-Idle', pkg: 'luci-app-hd-idle', desc: '硬盘休眠', version: 'v1.0', features: '节能保护、定时休眠、延长寿命'},
        {name: 'PartExp', pkg: 'luci-app-partexp', desc: '分区扩容', version: 'v1.0', features: '调整大小、移动分区、无损扩容'},
        {name: 'AccessControl', pkg: 'luci-app-accesscontrol-plus', desc: '访问控制', version: 'v1.0', features: 'MAC 过滤、时间段限制、设备管理'},
        {name: 'ParentControl', pkg: 'luci-app-parentcontrol', desc: '家长控制', version: 'v1.0', features: '网站过滤、时间管理、健康上网'},
        {name: 'TimeControl', pkg: 'luci-app-nft-timecontrol', desc: '上网时间控制', version: 'v1.0', features: '定时断网、学习计划、时间管理'},
        {name: 'Guest WiFi', pkg: 'luci-app-guest-wifi', desc: '访客 WiFi', version: 'v1.0', features: '隔离网络、临时密码、安全管理'},
        {name: 'WiFi Schedule', pkg: 'luci-app-wifischedule', desc: 'WiFi 计划', version: 'v1.0', features: '定时开关、节能模式、自动管理'},
        {name: 'TaskPlan', pkg: 'luci-app-taskplan', desc: '定时任务', version: 'v1.0', features: '定时执行、开机任务、循环执行'},
        {name: 'TimedReboot', pkg: 'luci-app-timedreboot', desc: '定时重启', version: 'v1.0', features: '计划任务、系统维护、自动重启'},
        {name: 'Watchcat', pkg: 'luci-app-watchcat', desc: '断网检测重启', version: 'v1.0', features: '网络监控、自动重启、故障恢复'},
        {name: 'TimeWOL', pkg: 'luci-app-timewol', desc: '网络唤醒', version: 'v1.0', features: '定时唤醒、远程开机、Wake-on-LAN'},
        {name: 'ARPBind', pkg: 'luci-app-arpbind', desc: 'ARP 绑定', version: 'v1.0', features: 'IP-MAC 绑定、防欺骗、网络安全'},
        {name: 'HomeAssistant', pkg: 'luci-app-homeassistant', desc: '智能家居', version: 'v1.0', features: '设备联动、自动化、智能控制'},
        {name: 'VLMCSD', pkg: 'luci-app-vlmcsd', desc: 'KMS 服务器', version: 'v1.0', features: 'Windows 激活、Office 激活、KMS 服务'},
        {name: 'CUPS', pkg: 'luci-app-cupsd', desc: '打印服务', version: 'v1.0', features: '网络打印、多打印机支持、打印管理'},
        {name: 'SNMPD', pkg: 'luci-app-snmpd', desc: 'SNMP 监控', version: 'v1.0', features: '设备管理、性能统计、网络监控'},
        {name: 'SubConverter', pkg: 'luci-app-subconverter', desc: '订阅转换', version: 'v1.0', features: '规则生成、节点筛选、格式转换'},
        {name: 'ACME', pkg: 'luci-app-acme', desc: 'HTTPS 证书', version: 'v1.0', features: '自动续签、多域名支持、Let\'s Encrypt'},
        {name: 'AirPlay2', pkg: 'luci-app-airplay2', desc: 'AirPlay2', version: 'v1.0', features: '音频流、多房间同步、无线播放'},
        {name: 'WeChatPush', pkg: 'luci-app-wechatpush', desc: '通知推送', version: 'v1.0', features: '微信推送、企业微信、消息通知'},
        {name: 'UnblockNeteaseMusic', pkg: 'luci-app-unblockneteasemusic', desc: '解锁网易云', version: 'v1.0', features: '版权歌曲、音源替换、音乐解锁'},
        {name: 'TVHelper', pkg: 'tvhelper', desc: '盒子助手', version: 'v1.0', features: '直播源管理、EPG 节目单、电视助手'},
        {name: 'Store', pkg: 'luci-app-store', desc: 'iStore 补充', version: 'v1.0', features: '应用商店、软件管理、扩展安装'}
    ]
};
