chip_group: generic
platform: ipq40xx
vendor: qualcomm

devices:
  - id: 8dev_habanero-dvk
    name: 8Dev Habanero-Dvk
  - id: 8dev_jalapeno
    name: 8Dev Jalapeno
  - id: alfa-network_ap120c-ac
    name: Alfa-Network Ap120C-Ac
  - id: aruba_ap-303
    name: Aruba Ap-303
  - id: aruba_ap-303h
    name: Aruba Ap-303H
  - id: aruba_ap-365
    name: Aruba Ap-365
  - id: asus_map-ac1300
    name: Asus Map-Ac1300
  - id: asus_map-ac2200
    name: Asus Map-Ac2200
  - id: asus_rt-ac42u
    name: Asus Rt-Ac42U
  - id: asus_rt-ac58u
    name: Asus Rt-Ac58U
  - id: avm_fritzbox-4040
    name: Avm Fritzbox-4040
  - id: avm_fritzbox-7530
    name: Avm Fritzbox-7530
  - id: avm_fritzrepeater-1200
    name: Avm Fritzrepeater-1200
  - id: avm_fritzrepeater-3000
    name: Avm Fritzrepeater-3000
  - id: buffalo_wtr-m2133hp
    name: Buffalo Wtr-M2133Hp
  - id: cellc_rtl30vw
    name: Cellc Rtl30Vw
  - id: cilab_meshpoint-one
    name: Cilab Meshpoint-One
  - id: compex_wpj428
    name: Compex Wpj428
  - id: devolo_magic-2-wifi-next
    name: Devolo Magic-2-Wifi-Next
  - id: dlink_dap-2610
    name: Dlink Dap-2610
  - id: edgecore_ecw5211
    name: Edgecore Ecw5211
  - id: engenius_eap1300
    name: Engenius Eap1300
  - id: extreme-networks_ws-ap3915i
    name: Extreme-Networks Ws-Ap3915I
  - id: extreme-networks_ws-ap391x
    name: Extreme-Networks Ws-Ap391X
  - id: ezviz_cs-w3-wd1200g-eup
    name: Ezviz Cs-W3-Wd1200G-Eup
  - id: glinet_gl-a1300
    name: Glinet Gl-A1300
  - id: glinet_gl-ap1300
    name: Glinet Gl-Ap1300
  - id: glinet_gl-b1300
    name: Glinet Gl-B1300
  - id: glinet_gl-b2200
    name: Glinet Gl-B2200
  - id: glinet_gl-s1300
    name: Glinet Gl-S1300
  - id: huawei_ap4050dn
    name: Huawei Ap4050Dn
  - id: linksys_ea6350v3
    name: Linksys Ea6350V3
  - id: linksys_ea8300
    name: Linksys Ea8300
  - id: linksys_mr6350
    name: Linksys Mr6350
  - id: linksys_mr8300
    name: Linksys Mr8300
  - id: linksys_whw01
    name: Linksys Whw01
  - id: linksys_whw03
    name: Linksys Whw03
  - id: linksys_whw03v2
    name: Linksys Whw03V2
  - id: luma_wrtq-329acn
    name: Luma Wrtq-329Acn
  - id: meraki_mr20
    name: Meraki Mr20
  - id: meraki_mr30h
    name: Meraki Mr30H
  - id: meraki_mr33
    name: Meraki Mr33
  - id: meraki_mr70
    name: Meraki Mr70
  - id: meraki_mr74
    name: Meraki Mr74
  - id: meraki_z3
    name: Meraki Z3
  - id: meraki_gx20
    name: Meraki Gx20
  - id: mobipromo_cm520-79f
    name: Mobipromo Cm520-79F
  - id: netgear_ex6100v2
    name: Netgear Ex6100V2
  - id: netgear_ex6150v2
    name: Netgear Ex6150V2
  - id: netgear_lbr20
    name: Netgear Lbr20
  - id: netgear_rbr20
    name: Netgear Rbr20
  - id: netgear_rbs20
    name: Netgear Rbs20
  - id: netgear_rbr40
    name: Netgear Rbr40
  - id: netgear_rbs40
    name: Netgear Rbs40
  - id: netgear_rbr50
    name: Netgear Rbr50
  - id: netgear_rbs50
    name: Netgear Rbs50
  - id: netgear_srr60
    name: Netgear Srr60
  - id: netgear_srs60
    name: Netgear Srs60
  - id: netgear_wac510
    name: Netgear Wac510
  - id: openmesh_a42
    name: Openmesh A42
  - id: openmesh_a62
    name: Openmesh A62
  - id: p2w_r619ac-64m
    name: P2W R619Ac-64M
  - id: p2w_r619ac-128m
    name: P2W R619Ac-128M
  - id: pakedge_wr-1
    name: Pakedge Wr-1
  - id: plasmacloud_pa1200
    name: Plasmacloud Pa1200
  - id: plasmacloud_pa2200
    name: Plasmacloud Pa2200
  - id: qxwlan_e2600ac-c1
    name: Qxwlan E2600Ac-C1
  - id: qxwlan_e2600ac-c2
    name: Qxwlan E2600Ac-C2
  - id: skspruce_wia3300-20
    name: Skspruce Wia3300-20
  - id: sony_ncp-hg100-cellular
    name: Sony Ncp-Hg100-Cellular
  - id: teltonika_rutx50
    name: Teltonika Rutx50
  - id: wallys_dr40x9
    name: Wallys Dr40X9
  - id: yyets_le1
    name: Yyets Le1
  - id: zte_mf18a
    name: Zte Mf18A
  - id: zte_mf282plus
    name: Zte Mf282Plus
  - id: zte_mf286d
    name: Zte Mf286D
  - id: zte_mf287
    name: Zte Mf287
  - id: zte_mf287plus
    name: Zte Mf287Plus
  - id: zte_mf287pro
    name: Zte Mf287Pro
  - id: zte_mf289f
    name: Zte Mf289F
  - id: zyxel_nbg6617
    name: Zyxel Nbg6617
