platform: qualcommax
vendor: qualcomm
description: "Qualcomm Atheros IPQ807x/IPQ60xx/IPQ50xx (WiFi 6/6E)"
kernel_patchver: "6.12"
source_branch: "main-nss"

subtargets:
  ipq807x:
    soc: ipq8072
    chips: [ipq8070, ipq8071, ipq8072, ipq8074, ipq8076, ipq8078]
    default_device: dynalink_dl-wrx36
    features: [squashfs, ext4, f2fs, nand, emmc, ramdisk, fpu, rtc]
    nss: true
  ipq60xx:
    soc: ipq6010
    chips: [ipq6000, ipq6010, ipq6018]
    default_device: 8devices_mango-dvk
    features: [squashfs, ext4, f2fs, nand, emmc, ramdisk, fpu, rtc]
    nss: true
  ipq50xx:
    soc: ipq5010
    chips: [ipq5010, ipq5018]
    default_device: generic
    features: [squashfs, ext4, nand, ramdisk]
    nss: true

packages:
  default:
    - nss-firmware-qualcommax
    - kmod-qca-nss-crypto
    - kmod-ath11k
    - kmod-ath11k-ahb
    - kmod-ath11k-pci
  ipq807x:
    - ath11k-firmware-ipq807x
  ipq60xx:
    - ath11k-firmware-ipq60xx
  ipq50xx:
    - ath11k-firmware-ipq50xx
  nss:
    - kmod-qca-nss-drv
    - kmod-qca-nss-ecm
    - kmod-qca-nss-dp
    - kmod-nss-ifb
    - kmod-qca-nss-drv-bridge-mgr
    - kmod-qca-nss-drv-pppoe
    - kmod-qca-nss-drv-vlan-mgr
    - kmod-qca-nss-drv-gre
    - kmod-qca-nss-drv-l2tpv2
    - kmod-qca-nss-drv-vxlanmgr
    - kmod-qca-nss-drv-mirror
    - kmod-qca-nss-drv-tunipip6
    - kmod-qca-nss-drv-wifi-meshmgr
  base:
    - luci-app-sqm
    - luci-app-diskman
    - luci-app-ledtrig-rssi
    - luci-app-ledtrig-switch
    - luci-app-ledtrig-usbport

constraints:
  firewall: [iptables, nftables]
  rootfs: [squashfs, ext4, f2fs]
  wifi: true
  emmc: true
